### ISSUE TITLE
Bridge solutions

### ISSUE THREAD

**Issue by Brunya** [zgendao/agora.space#29]
Look around among telegram-discord bridge solutions.
Should we implement it ourselves or should we use some OS package?

We may implement other communication platforms in the future not just DC and TG.

**Comment by dezsim** [comment]
**Possibilites for telegram-discord bridge:**

- matterbridge - https://github.com/42wim/matterbridge
- TediCross - https://github.com/TediCross/TediCross  ( not developed for a while, only dc - tg implementation )

There are a few other small projects, but I would say, we can't really rely on them, even if we want to grab other communication platforms in later on. 

While I was researching, I found the matrix.org which is a decentralised, secure, real-time communication platform with E2E encryption, and they are using matterbridge as well for bridging the communication. In my opinion, self implementation might require a lot of time,so we should try implementing discord - telegram bridge with the matterbridge, because for this purpose with multiple platforms, it's like our number#1 choice. Even our customers later on could self-host the runners, and the matterbridge based on an example repository or dockerized as well.
